export const controls = document.getElementById("controls")
export const sounds = document.getElementById("sounds")
export const startButton = document.getElementById("start")
export const pauseButton = document.getElementById("pause")
export const timerSpan = document.getElementById("timer")